In [13]:
import numpy as np

In [14]:
my_lst = [1, 2, 3, 4, 5]

arr = np.array(my_lst)

In [15]:
type(arr)

numpy.ndarray

In [16]:
print(arr)

[1 2 3 4 5]


In [17]:
arr.shape

(5,)

In [18]:
arr.ndim

1

In [19]:
type(arr)

numpy.ndarray

In [20]:
my_lst1 = [1,2,3,4,5]
my_lst2 = [4,5,6,7,8]
my_lst3 = [7,8,9,10,11]

In [22]:
arr = np.array([my_lst1, my_lst2, my_lst3])

In [23]:
print(arr)

[[ 1  2  3  4  5]
 [ 4  5  6  7  8]
 [ 7  8  9 10 11]]


In [24]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 4,  5,  6,  7,  8],
       [ 7,  8,  9, 10, 11]])

In [28]:
arr.reshape(5,3)

array([[ 1,  2,  3],
       [ 4,  5,  4],
       [ 5,  6,  7],
       [ 8,  7,  8],
       [ 9, 10, 11]])

In [26]:
arr.shape

(3, 5)

INDEXING

In [30]:
#ACCESSING THE ARRAY ELEMENTS

arr

array([[ 1,  2,  3,  4,  5],
       [ 4,  5,  6,  7,  8],
       [ 7,  8,  9, 10, 11]])

In [33]:
arr = np.array([1,2,3,4,5,6,7,8,9])

In [34]:
arr[3]

4

In [39]:
arr = np.array([my_lst1, my_lst2, my_lst3])

In [40]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 4,  5,  6,  7,  8],
       [ 7,  8,  9, 10, 11]])

In [38]:
arr[0:2,0:2]

array([[1, 2],
       [4, 5]])

In [47]:
arr[1:,3:]

array([[ 7,  8],
       [10, 11]])

In [51]:
arr[1:, 2:4]

array([[ 6,  7],
       [ 9, 10]])

In [55]:
arr[2, 2]


9

In [56]:
arr[0:2, 3:]

array([[4, 5],
       [7, 8]])

In [59]:
arr[1,2:4]

array([6, 7])

In [ ]:
arr = np.arange(0, 10)

In [61]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
np.linspace(1,10,50)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [ ]:
## copy function and broadcasting


arr[:3] = 100

In [66]:
arr

array([100, 100, 100,   3,   4,   5,   6,   7,   8,   9])

In [67]:
arr1 = arr

In [68]:
arr1[3:] = 500

In [69]:
print(arr1)

[100 100 100 500 500 500 500 500 500 500]


In [70]:
arr1 = arr.copy()

In [71]:
print(arr)

[100 100 100 500 500 500 500 500 500 500]


In [73]:
arr1[3:] = 1000

In [74]:
print(arr1)

[ 100  100  100 1000 1000 1000 1000 1000 1000 1000]
