In [13]:
import numpy as np

In [14]:
my_lst = [1, 2, 3, 4, 5]

arr = np.array(my_lst)

In [15]:
type(arr)

numpy.ndarray

In [16]:
print(arr)

[1 2 3 4 5]


In [17]:
arr.shape

(5,)

In [18]:
arr.ndim

1

In [19]:
type(arr)

numpy.ndarray

In [20]:
my_lst1 = [1,2,3,4,5]
my_lst2 = [4,5,6,7,8]
my_lst3 = [7,8,9,10,11]

In [22]:
arr = np.array([my_lst1, my_lst2, my_lst3])

In [23]:
print(arr)

[[ 1  2  3  4  5]
 [ 4  5  6  7  8]
 [ 7  8  9 10 11]]


In [24]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 4,  5,  6,  7,  8],
       [ 7,  8,  9, 10, 11]])

In [28]:
arr.reshape(5,3)

array([[ 1,  2,  3],
       [ 4,  5,  4],
       [ 5,  6,  7],
       [ 8,  7,  8],
       [ 9, 10, 11]])

In [26]:
arr.shape

(3, 5)

INDEXING

In [30]:
#ACCESSING THE ARRAY ELEMENTS

arr

array([[ 1,  2,  3,  4,  5],
       [ 4,  5,  6,  7,  8],
       [ 7,  8,  9, 10, 11]])

In [33]:
arr = np.array([1,2,3,4,5,6,7,8,9])

In [34]:
arr[3]

4